

---

- hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:

  - name: Installation de python-apt pour utiliser des apt get plus tard
    raw: apt-get install python -y && apt-get install python-apt -y   






